# Generated by Django 2.2 on 2020-06-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posttag',
            unique_together={('post_id', 'tag_id')},
        ),
    ]
