# Generated by Django 2.2 on 2020-06-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0002_auto_20200612_0915'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posttag',
            unique_together=set(),
        ),
    ]
