# Generated by Django 2.2 on 2020-06-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0003_auto_20200613_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_api.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='posttag',
            unique_together={('post_id', 'tag_id')},
        ),
    ]
