# Generated by Django 2.2 on 2020-06-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0004_auto_20200613_0741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTag',
            new_name='PostTagRelation',
        ),
    ]
