# Generated by Django 2.2 on 2020-06-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0005_auto_20200613_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='PostTag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_category',
            new_name='category',
        ),
    ]
