# Generated by Django 2.2 on 2020-06-14 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0007_auto_20200614_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_api.Post'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='post_api.Post'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
