# Generated by Django 2.2 on 2020-06-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0008_auto_20200614_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post_api.Post'),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
