# Generated by Django 2.2 on 2020-06-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0010_post_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_profile',
        ),
    ]
