# Generated by Django 2.2 on 2020-06-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0014_delete_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postbookmark',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='postbookmark',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='postreport',
            name='category',
        ),
        migrations.RemoveField(
            model_name='postreport',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='postreport',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='CommentReport',
        ),
        migrations.DeleteModel(
            name='PostBookmark',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.DeleteModel(
            name='PostReport',
        ),
        migrations.DeleteModel(
            name='ReportCategory',
        ),
    ]
