# Generated by Django 2.2 on 2020-06-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0016_postcomment2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment2',
        ),
    ]
