# Generated by Django 2.2 on 2020-06-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0017_delete_postcomment2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimages',
            old_name='title',
            new_name='image_title',
        ),
    ]
