# Generated by Django 2.2 on 2020-06-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0018_auto_20200615_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimages',
            old_name='image_title',
            new_name='title',
        ),
    ]
