# Generated by Django 2.2 on 2020-06-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0019_auto_20200615_1153'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posttagrelation',
            unique_together=set(),
        ),
    ]
