# Generated by Django 2.2 on 2020-06-16 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0024_auto_20200616_2241'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='post_api_po_categor_f13fac_idx',
        ),
    ]
