# Generated by Django 2.2 on 2020-07-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0026_auto_20200616_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_profile',
            new_name='user',
        ),
    ]
