# Generated by Django 2.2 on 2020-07-01 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0027_auto_20200701_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='Content', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
