# Generated by Django 2.2 on 2020-07-01 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0028_auto_20200701_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimages',
            old_name='alt_text',
            new_name='image_path',
        ),
        migrations.RemoveField(
            model_name='postimages',
            name='description',
        ),
        migrations.AlterField(
            model_name='postimages',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
