# Generated by Django 2.2 on 2020-07-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0030_auto_20200701_1031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTagRelation',
            new_name='PostTag',
        ),
    ]
