# Generated by Django 2.2 on 2020-07-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0031_auto_20200701_1036'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='post_api_po_categor_f13fac_idx',
        ),
    ]
