# Generated by Django 2.2 on 2020-07-03 16:35

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0032_auto_20200703_1626'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['category'], name='post_api_po_categor_aefd09_brin'),
        ),
    ]
