# Generated by Django 2.2 on 2020-07-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0035_auto_20200703_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_content',
            field=models.CharField(default='Something Here', max_length=255),
            preserve_default=False,
        ),
    ]
