# Generated by Django 2.2 on 2020-07-03 16:53

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0036_post_title_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_content',
        ),
        migrations.AddField(
            model_name='post',
            name='title_content_search',
            field=django.contrib.postgres.search.SearchVectorField(default='content', max_length=255),
            preserve_default=False,
        ),
    ]
