# Generated by Django 2.2 on 2020-07-03 16:54

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0037_auto_20200703_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_content_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
