# Generated by Django 2.2 on 2020-07-03 16:54

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0038_auto_20200703_1654'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_content_search'], name='post_api_po_title_c_897072_gin'),
        ),
    ]
