# Generated by Django 2.2 on 2020-07-03 18:44

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0039_auto_20200703_1654'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='post_api_po_title_c_897072_gin',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_content_search',
            new_name='full_title_content',
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_title_content'], name='post_api_po_full_ti_070405_gin'),
        ),
    ]
