# Generated by Django 2.2 on 2020-07-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0040_auto_20200703_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
