# Generated by Django 2.2 on 2020-07-01 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timebanking_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentbalance',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user_to_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_from_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_from_transaction', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentbalance',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
