# Generated by Django 2.2 on 2020-07-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebanking_api', '0002_auto_20200701_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
