# Generated by Django 2.2 on 2020-07-01 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timebanking_api', '0004_auto_20200701_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_balance', to=settings.AUTH_USER_MODEL),
        ),
    ]
