# Generated by Django 2.2 on 2020-06-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_profile',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='profileimage',
            old_name='user_profile',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255),
        ),
    ]
