# Generated by Django 2.2 on 2020-06-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20200616_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user_profile',
        ),
    ]
