# Generated by Django 2.2 on 2020-07-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_auto_20200616_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='date_joined',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
