# Generated by Django 2.2 on 2020-07-01 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0013_auto_20200701_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
