# Generated by Django 2.2 on 2020-07-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0017_auto_20200701_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_balance',
        ),
    ]
