# Generated by Django 2.2 on 2020-07-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0018_remove_userprofile_current_balance'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['id'], name='profiles_ap_id_992ad2_idx'),
        ),
    ]
