# Generated by Django 2.2 on 2020-06-15 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_interaction_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbookmark',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_bookmarks', to='post_api.Post'),
        ),
        migrations.AlterField(
            model_name='postbookmark',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postuser_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postuser_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
