# Generated by Django 2.2 on 2020-06-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_interaction_api', '0002_auto_20200615_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcommentreport',
            old_name='user_id',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='postreport',
            old_name='user_id',
            new_name='user_profile',
        ),
    ]
