# Generated by Django 2.2 on 2020-06-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_interaction_api', '0003_auto_20200615_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcommentreport',
            old_name='user_profile',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='postreport',
            old_name='user_profile',
            new_name='user_id',
        ),
    ]
