# Generated by Django 2.2 on 2020-06-16 07:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0019_auto_20200615_1153'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_interaction_api', '0004_auto_20200615_1428'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postbookmark',
            unique_together={('post_id', 'user_id')},
        ),
    ]
