# Generated by Django 2.2 on 2020-06-16 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_interaction_api', '0005_auto_20200616_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbookmark',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_bookmarkslist', to='post_api.Post'),
        ),
        migrations.AlterField(
            model_name='postbookmark',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmarkslist', to=settings.AUTH_USER_MODEL),
        ),
    ]
