# Generated by Django 2.2 on 2020-06-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_interaction_api', '0006_auto_20200616_0757'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postbookmark',
            unique_together=set(),
        ),
    ]
